apiVersion: apps/v1
kind: Deployment
metadata:
  name: new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: new2
  template:
    metadata:
      labels:
        app: new2
    spec:
      containers:
      - name: new2
        image: varunr1/smartapp:v1
        command: ["/main"]
        ports:
        - containerPort: 8022
        securityContext:
          runAsUser: 0

